language: node_js
node_js:
  - '6'
install:
  - npm install
script:
  - npm test
  - npm run build
after_success:
    - "curl --ftp-create-dirs -T index.html -u $FTP_USER:$FTP_PASSWORD ftp://carehr.nl/public_html/kookcalc/"
    - "curl --ftp-create-dirs -T main.js -u $FTP_USER:$FTP_PASSWORD ftp://carehr.nl/public_html/kookcalc/"
    - "curl --ftp-create-dirs -T vendor.js -u $FTP_USER:$FTP_PASSWORD ftp://carehr.nl/public_html/kookcalc/"
    - "curl --ftp-create-dirs -T style.css -u $FTP_USER:$FTP_PASSWORD ftp://carehr.nl/public_html/kookcalc/"
